# 应用管理
"application-management": "应用管理"
"application-management.application-template": "应用模板"
"application-management.application": "应用"
"application-management.application-version": "应用版本"
"application-management.application-release": "应用发布"
"application-management.application-market": "应用市场"

# 开发流水线
"development-pipeline": "开发流水线"
"development-pipeline.branch": "分支"
"development-pipeline.tag": "标记"
"development-pipeline.repository": "代码仓库"
"development-pipeline.merge-request": "合并请求"
"development-pipeline.continuous-integration": "持续集成"

# 部署流水线
"deployment-pipeline": "部署流水线"
"deployment-pipeline.environment-pipeline": "环境流水线"
"deployment-pipeline.application-deployment": "应用部署"
"deployment-pipeline.instance": "实例"
"deployment-pipeline.service": "网络"
"deployment-pipeline.ingress": "域名"
"deployment-pipeline.container": "容器"

